  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cc-api
      namespace: dcp-prod
    data:
      DIRECTORY_URL: 'https:///directory-service.adsp.alberta.ca'
      KEYCLOAK_ROOT_URL: 'https://access.alberta.ca'
      LOG_LEVEL: debug
      PORT: "3333"
  - apiVersion: v1
    kind: Secret
    metadata:
      name: cc-api
      namespace: dcp-prod
    stringData:
      CLIENT_ID: 
      CLIENT_SECRET: 
      REALM: 