  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${APP_NAME}
      namespace: ${PROJECT}
    data:
      DIRECTORY_URL: 'https://directory-service.adsp-uat.alberta.ca'
      KEYCLOAK_ROOT_URL: 'https://access-uat.alberta.ca'
      LOG_LEVEL: debug
      PORT: "3333"