  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${APP_NAME}
      namespace: ${PROJECT}
    stringData:
      CLIENT_ID: urn:ads:digital_marketplace:public
      REALM: 9ddc3790-b16d-48f6-be99-3a5c6ea71326
      CLIENT_SECRET: