apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: dcp-proxy-api-int
labels:
  app: dcp-proxy-api-int
parameters:
  - name: INFRA_PROJECT
    description: Project used for build infrastructure.
    displayName: Infrastructure Project
    value: dcp-build
    required: true
  - name: PROJECT
    description: Project to set up.
    displayName: Project
    required: true
  - name: APP_NAME
    description: Name of the application.
    displayName: Application Name
    value: dcp-proxy-api-int
    required: true
  - name: DEPLOY_TAG
    description: Tag of the ImageStream to deploy.
    displayName: Deploy Tag
    value: latest
    required: true
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APP_NAME}
      namespace: ${PROJECT}
    spec:
      ports:
        - name: http
          port: 3333
          protocol: TCP
          targetPort: 3333
      selector:
        name: ${APP_NAME}
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        apply-build: 'true'
      name: ${APP_NAME}
      namespace: ${INFRA_PROJECT}
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        apply-build: 'true'
      name: ${APP_NAME}
      namespace: ${INFRA_PROJECT}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: '${APP_NAME}:latest'
      resources:
        limits:
          cpu: 300m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 200Mi
      runPolicy: Serial
      source:
        binary: {}
        type: Binary
      strategy:
        dockerStrategy:
          buildArgs:
            - name: PROJECT
              value: dcp-proxy-api-int
          dockerfilePath: .openshift/dcp-proxy-api-int/Dockerfile
        type: Docker
      triggers: []
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${APP_NAME}
      namespace: ${PROJECT}
      annotations:
        image.openshift.io/triggers: |-
          [
            {
              "from": {
                "kind": "ImageStreamTag",
                "name": "${APP_NAME}:${DEPLOY_TAG}",
                "namespace": "${INFRA_PROJECT}"
              },
              "fieldPath": "spec.template.spec.containers[0].image",
              "paused": true
            }
          ]
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: ${APP_NAME}
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
      template:
        metadata:
          labels:
            name: ${APP_NAME}
        spec:
          containers:
            - name: ${APP_NAME}
              image: ${APP_NAME}:${DEPLOY_TAG}
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}
                - secretRef:
                    name: ${APP_NAME}
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 3333
                  name: http
                  protocol: TCP
              resources:
                limits:
                  cpu: 200m
                  memory: 200Mi
                requests:
                  cpu: 20m
                  memory: 50Mi
              terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${APP_NAME}
      namespace: ${PROJECT}
    spec:
      port:
        targetPort: http
      tls:
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}
        weight: 100
      wildcardPolicy: None