
// Please note: Sort is automaticlly done in the app.
// All new term can be added at the bottom

export const glossaryItems = [

    { term : 'Accessibility', definition: 'Ensuring that digital services are usable by people of all abilities and disabilities, including compliance with standards like WCAG 2.0 to make services inclusive.' },
    { term : 'Accessibility', definition: 'Everyone who needs to use a government digital service or website should be able to use it. This includes people with visual, hearing, cognitive or motor impairments, those with learning difficulties, and older people. It also includes people with different levels of digital confidence and access to a digital environmen' },
    { term : 'Accessibility and inclusivity', definition: 'Software should be accessible and usable by all citizens, regardless of their abilities and disabilities. This includes ensuring the software is compatible with assistive technologies and adhering to accessibility standards such as the Web Content Accessibility Guidelines (WCAG). In addition, we would want to support inclusiveness and representation of diverse perspectives' },
    { term : 'Accessibility Compliance', definition: 'Adherence to standards ensuring that digital services are accessible to all users, including those with disabilities.' },
    { term : 'Accessible', definition: 'Digital products will be usable for the broadest range of users possible regardless of physical or cognitive limitations, literacy level, or technical capability' },
    { term : 'Adaptability', definition: 'Because of the incremental nature and short work cycles, products can adapt as information changes. With Waterfall, all requirements are collected upfront and the product is built based on those requirements!' },
    { term : 'Adoption and Usage Metrics', definition: 'Statistics that track the number of users engaging with a digital service, how often they use it, and the extent of their interactions, reflecting its overall impact.' },
    { term : 'Adoption Cost', definition: 'The total expenditure and resources required for citizens, businesses, or other government entities to transition to and effectively use a new digital service.' },
    { term : 'Adoption Cost', definition: 'The total expenditure and resources required for citizens, businesses, or other government entities to transition to and effectively use a new digital service.' },
    { term : 'Adoption Rate', definition: 'Measures the percentage of total service transactions conducted via digital channels compared to non-digital channels.' },
    { term : 'Agile', definition: 'A flexible and iterative project management methodology that emphasizes collaboration, customer feedback, and small, rapid releases to adapt to changing requirements and deliver value.' },
    { term : 'Agile', definition: 'A flexible and iterative project management methodology that emphasizes collaboration, customer feedback, and small, rapid releases to adapt to changing requirements and deliver value.' },
    { term : 'Agile Adoption Rate', definition: 'Measures the percentage of projects adopting agile methodologies.' },
    { term : 'Agile and iterative approach', definition: 'Software development efforts should adopt an agile and iterative approach to ensure that software is delivered quickly and can adapt to changing requirements.' },
    { term : 'Agile Maturity Score', definition: 'Assesses the maturity of agile practices within the organization.' },
    { term : 'Agile solutions for future readiness', definition: 'The chosen tools and technologies offer flexibility and adaptability to accommodate changes in technology trends, business requirements, or user preferences. They allow you to iterate, evolve, and pivot as needed throughout the product lifecycle. ' },
    { term : 'Agile Teams', definition: 'Is a cross functional group of typiocally ten or fewer individuals with all the skills necessary to define, build, test, and deliver value to their customers. ' },
    { term : 'Agile teams', definition: 'Multidisciplinary teams that use iterative, flexible development practices to rapidly respond to user feedback and changing requirements.' },
    { term : 'Alberta Design', definition: 'Design your service using reusable patterns, components, tokens, and content guidelines.' },
    { term : 'Alberta.ca account', definition: 'Use these resources to build your service. Learn from the research and experience of other service teams and avoid repeating work that’s already been done.' },
    { term : 'Alberta.ca account', definition: 'An Alberta.ca Account enables people to access government digital services online. An Alberta.ca Account lets people sign in to their Alberta.ca Account using an account they already have.' },
    { term : 'Alpha', definition: 'The Alberta.ca account is an essential platform for businesses in Alberta to interact with the government and is currently going through a re-platforming by the IAM team. This replatforming initiative opens up future opportunities for improvement, such as a more efficient experience, more accessible and simpler language. ' },
    { term : 'Availability of Services Online', definition: 'An Alberta.ca Account provides you with secure access to multiple government programs and services. Your Alberta.ca Account lets you sign in once for seamless access to participating services across government. It also gives you a secure way to verify who you are online without paper documents or face-to-face visits, while protecting your information and privacy.' },
    { term : 'Baseline Performance Measures', definition: 'Developing and testing our hypotheses with users' },
    { term : 'Benchmarking', definition: 'Measured by the percentage of government services available online.' },
    { term : 'Beta', definition: 'Initial measures captured to establish a starting point for assessing improvements.' },
    { term : 'Budget Variance', definition: 'Comparing service performance against similar services within and outside the organization to identify areas for improvement.' },
    { term : 'Business Value', definition: 'Developing a minimum viable service and making it available to the public' },
    { term : 'Change Management', definition: 'Measures the difference between the budgeted cost and the actual cost of projects.' },
    { term : 'Collaboration and engagement', definition: 'A useable product is produced early on in the process and is then improved through the remainder of the process (MVP). With Waterfall - minimal value until the end of the process. ' },
    { term : 'Common Capabilities', definition: 'The practice of managing changes to services effectively to minimize disruption and maximize benefits.' },
    { term : 'Common Components', definition: 'Software development efforts should be collaborative and engage with citizens, stakeholders, and other relevant parties. This includes conducting user field research to better understand their needs and involving them in the design and development process.' },
    { term : 'Common components', definition: 'Common capabilities is designed for developers and solution architects to explore existing services and technology used within GoA, circulate best practices, and deliver meaningful experiences to all Albertans.' },
    { term : 'Common components', definition: 'Reusable parts of the user interface for content layout, feedback, alerts, inputs, actions, structure, navigation, and other utilities.' },
    { term : 'Common Platform', definition: 'Reusable software modules or systems that can be used across different digital services to ensure consistency and reduce development costs.' },
    { term : 'Community-driven support', definition: 'Common components are typically software or technical systems created once and reused many times in different services or business contexts.' },
    { term : 'Compliance', definition: 'Common platform system means information system shared by multiple agencies, excluding such information systems whose entire operations including hardware and software are controlled and managed by a single agency.' },
    { term : 'Compliance Audits', definition: 'The tools and technologies have a vibrant community of users, developers, and contributors who provide support, resources, and documentation. Access to community forums, knowledge bases, and tutorials can facilitate learning, troubleshooting, and collaboration.' },
    { term : 'Compliance with relevant regulations', definition: 'Adherence to relevant standards, regulations, and guidelines to ensure quality and legality of digital services.' },
    { term : 'Compliant', definition: 'Regular reviews to ensure digital services meet all relevant standards and regulations.' },
    { term : 'Continuous Evaluation and Improvement', definition: 'Software development efforts should comply with relevant regulations and standards, such as data protection regulations, accessibility standards, and procurement regulations.' },
    { term : 'Continuous Improvement', definition: 'Digital products will align as much as possible to organizational policies such as brand, information management, cyber security, and other Government of Alberta recommended practices.' },
    { term : 'Cost Effectiveness', definition: 'Regularly evaluate and reassess the suitability of the chosen tools and technologies throughout the product lifecycle. Monitor performance, gather feedback, and stay informed about emerging trends and innovations to identify opportunities for optimization and enhancement.  ' },
    { term : 'Cost per Agile Project', definition: 'Ongoing efforts to enhance digital services based on performance data and user feedback.' },
    { term : 'Cost per Transaction', definition: 'The total cost of ownership (TCO) of the tools and technologies aligns with the budget and delivers value relative to the investment. Consider both upfront costs and ongoing expenses, including licensing fees, maintenance, training, and support.' },
    { term : 'Cost Savings from digitization', definition: 'Measures the average cost of completing an agile project.' },
    { term : 'Cost-Benefit Analysis', definition: 'The amount it costs the government each time a user completes a transaction through the service.' },
    { term : 'Cross-Departmental Collaboration', definition: 'Measures the amount of cost savings achieved by shifting services from traditional methods to digital channels.' },
    { term : 'Customer Value', definition: 'Assessing the financial viability and overall benefits of a digital service relative to its costs.' },
    { term : 'Cybersecurity Strategy', definition: 'Working with multiple departments or ministries to deliver integrated and cohesive digital services.' },
    { term : 'Data analysis', definition: 'The value derived by customers from using a digital service, reflecting its effectiveness and relevance.' },
    { term : 'Data Analysis', definition: 'A comprehensive approach to protecting digital services and user data from cyber threats and ensuring secure service delivery.' },
    { term : 'Data Governance', definition: 'The process of examining and interpreting data to gain insights and inform decision-making for service improvement.' },
    { term : 'Data Management', definition: 'The process of examining and interpreting data to gain insights and inform decision-making for service improvement.' },
    { term : 'Data Segmentation', definition: 'Policies and practices for managing data availability, usability, integrity, and security in digital services.' },
    { term : 'Data Sharing', definition: 'Ensure that the tools and technologies support effective data management, including data governance, data lifecycle, and data and process residency.' },
    { term : 'Data Steward', definition: 'Dividing data into segments based on different criteria (e.g., device type, user type) to understand trends and behaviors.' },
    { term : 'Data stewardship', definition: 'Sharing performance data with stakeholders to maintain transparency and inform decision-making.' },
    { term : 'Data Visualization', definition: 'Data users who implement enterprise data governance and principles to control the use and maintenance of data assets.' },
    { term : 'Design System', definition: 'Responsible management and use of data, ensuring its accuracy, privacy, security, and appropriate sharing.' },
    { term : 'Digital', definition: 'Using charts, graphs, and other visual tools to represent performance metrics and insights for digital services.' },
    { term : 'Digital Credentials', definition: 'A collection of design standards, components, and guidelines used to create consistent and cohesive digital experiences.' },
    { term : 'Digital Credentials', definition: 'Applying the culture, practices, processes & technologies of the Internet-era to respond to people\'s raised expectations' },
    { term : 'Digital Experience Standard', definition: 'Representations of credentials issued to individuals or organizations. Defined by a standardized specification agreed to by other parties and signed using public key cryptography to ensure its authenticity' },
    { term : 'Digital Inclusion Rate', definition: 'In the physical world, your driver’s licence or health card allows you to provide information about yourself, what you can do, or what services you can access; digital credentials would be the digital equivalent of these documents.' },
    { term : 'Digital Maturity', definition: 'Specific guidelines and best practices for creating consistent and high-quality digital experiences.' },
    { term : 'Digital Privacy', definition: 'Measures the percentage of the population with access to digital services, including underserved and rural communities.' },
    { term : 'Digital Security', definition: 'The level of sophistication and effectiveness of an organization\'s digital capabilities and practices.' },
    { term : 'Digital Service Principles', definition: 'Safeguarding personal information from unlawful data collection and ensuring user control over personal data.' },
    { term : 'Digital Service Standards', definition: 'Protection against unauthorized access of data, often involving safeguarding against hackers or cyber criminals. ' },
    { term : 'Digital Service Usage Rate / Adoption Rate', definition: 'Foundational guidelines that inform and shape the creation of Digital Service Standards, focusing on user needs, accessibility, continuous improvement, among others.' },
    { term : 'Digital Take-Up', definition: 'A set of best practices, policies, or guidelines for designing and delivering digital government services, which are measurable and have clear accountabilities.' },
    { term : 'Digital Transformation', definition: 'Measures the percentage of total service transactions conducted via digital channels (e.g., online portals, mobile apps) compared to traditional methods (e.g., in-person, telephone).' },
    { term : 'Discovery Phase', definition: 'The percentage of users choosing the digital service over non-digital channels to complete their task.' },
    { term : 'Efficiency Improvement Rate', definition: 'The process of using digital technologies to fundamentally change how services are delivered and experienced.' },
    { term : 'Encouragement of feedback and Continuous improvement', definition: 'Discovery helps define a service’s potential users and how their needs can be met.' },
    { term : 'End-to-end testing', definition: 'Measures the percentage improvement in efficiency metrics (e.g., processing time, user satisfaction) following the implementation of agile practices.' },
    { term : 'End-to-end testing', definition: 'Software development efforts should continuously improve, incorporating feedback and new technologies to enhance the user experience and deliver better services to citizens. In addition, we would like to encourage digital literacy and access to technology for citizens.' },
    { term : 'End-to-End Testing', definition: 'Comprehensive testing of digital services from start to finish to ensure seamless, reliable user experiences.' },
    { term : 'End-User Context', definition: 'End-to-end (E2E) testing is a software testing methodology that verifies the working order of a software product in a start-to-finish process.' },
    { term : 'End-User Training', definition: 'Thorough testing of a digital service from start to finish to ensure it meets user needs and performs reliably.' },
    { term : 'Error Rate', definition: 'The various contexts in which end-users interact with the service, influencing its performance.' },
    { term : 'Ethical considerations', definition: 'Providing users with the knowledge and skills needed to effectively use digital services.' },
    { term : 'Feedback Loops', definition: 'Measures the percentage of service transactions that encounter errors.' },
    { term : 'Feedback Mechanisms', definition: 'Ensuring digital services are designed and implemented in a way that is fair, non-discriminatory, and respects user rights and dignity.' },
    { term : 'Financial Controls', definition: 'Mechanisms for continuously collecting and incorporating user feedback into the service development process.' },
    { term : 'Financial Data Analysis', definition: 'Systems and processes for collecting and responding to user feedback to drive service improvements.' },
    { term : 'Help Desk Metrics', definition: 'Financial oversight and monitoring implemented to ensure the service delivery cycle is cost-effective.' },
    { term : 'Historical Data Analysis', definition: 'Reviewing financial information, such as hosting costs, to assess cost-efficiency and budget allocation.' },
    { term : 'Holders', definition: 'Data collected from service desks or call centers, such as the number of support calls and types of issues reported.' },
    { term : 'Holistic insights', definition: 'Reviewing past performance data to identify long-term trends and inform future improvements.' },
    { term : 'Holistic Insights', definition: 'Individuals who are transferred the digital credential from the issuer to their wallet client to present the credential to the verifier (e.g., an Albertan resident).' },
    { term : 'Hypothesis Testing', definition: 'Comprehensive understanding gained from considering diverse perspectives and factors affecting users and their experiences.' },
    { term : 'Identifiers', definition: 'Comprehensive understanding of user needs and behaviors obtained through various research methods.' },
    { term : 'Incident Response', definition: 'Creating and testing hypotheses to measure the impact of specific actions or changes on service performance.' },
    { term : 'Inclusion', definition: 'Parties responsible for establishing the authenticity of individuals or organizations in the process of provisioning a digital credential (e.g., Alberta.ca Account).' },
    { term : 'Inclusive Definition of Success', definition: 'The process of addressing and managing incidents that affect digital service performance.' },
    { term : 'Inclusive digital experiences', definition: 'Designing services to be usable by a diverse range of people, considering various demographic backgrounds and needs.' },
    { term : 'Information Controller', definition: 'Defining success in a way that includes a wide range of metrics and perspectives, ensuring a holistic view.' },
    { term : 'Information Custodian', definition: 'Digital services designed to be accessible and usable by all people, regardless of their abilities or backgrounds.' },
    { term : 'Information Technology', definition: 'Information controllers have the responsibility and decision-making authority for assigned collections of information, including (but not limited to) regulating and administering use, disclosure, and/or disposition of information.' },
    { term : 'Information Technology Asset', definition: 'Information custodians have the responsibility for maintaining and/or administering the systems and/or applications in which information is managed without having responsibility for the information itself.' },
    { term : 'Innovation', definition: 'The equipment, software, services and processes used to create, store, process, communicate and manage information.' },
    { term : 'Interoperability', definition: 'Includes owned and leased technology hardware (i.e. physical items), owned or licensed software and related or supporting services' },
    { term : 'Interoperability and integration', definition: 'Encouraging the use of new ideas and approaches to improve digital services.' },
    { term : 'Interoperable', definition: 'The capability of a digital service to work seamlessly with other systems and services.' },
    { term : 'Issuer Control ', definition: 'The tools and technologies integrate seamlessly with existing systems, platforms, or workflows within GoA. They support interoperability and integration with other systems, reducing friction and enabling smooth collaboration across teams.' },
    { term : 'Issuers', definition: 'The ability of different systems and technologies to work together seamlessly and exchange information effectively.' },
    { term : 'IT Governance', definition: 'The principle that the issuer of a credential should be able to revoke it in certain situations (e.g., an individual loses their driving privileges).' },
    { term : 'Iterative', definition: 'Parties who own the source of truth for a credential and provision that source of truth into its digital representation. (e.g., Alberta Health).' },
    { term : 'Iterative development', definition: 'The structure of policies, roles, and procedures that ensure effective management and oversight of digital services.' },
    { term : 'Iterative development', definition: 'Products are continuously tested, resourced, and improved upon with user input and usage data to ensure lasting effectiveness, efficiency, and usability' },
    { term : 'Key Performance Indicators (KPIs)', definition: 'A process of continuously improving and evolving digital services through repeated cycles of development, testing, and feedback.' },
    { term : 'Key Performance Indicators (KPIs)', definition: 'Iterative development means to work with iterations which are smaller and more manageable components of a project.' },
    { term : 'Key Performance Indicators (KPIs)', definition: 'Metrics used to measure the success and performance of digital services across various dimensions such as cost, adoption, and user satisfaction.' },
    { term : 'KPI Dashboards', definition: 'Key performance indicators are a measurement tool used to measure employee and company performance.' },
    { term : 'Live', definition: 'Metrics used to measure the success and performance of digital services across various dimensions such as cost, adoption, and user satisfaction.' },
    { term : 'Minimum Viable Product (MVP)', definition: 'Visual representations of key performance indicators for monitoring and managing digital service performance.' },
    { term : 'Ministry Business Plan', definition: 'Continuing to improve based on user feedback' },
    { term : 'Monitoring and Reporting', definition: 'An MVP (Minimum Viable Product) is an initial version of a product focused on meeting the main user need. Unlike a prototype or POC, it is a complete product for the end consumer, developed in an agile manner. The MVP seeks the product-market fit, assessing demand and interest, with the essentials already present.' },
    { term : 'Multidisciplinary teams', definition: 'A Ministry Business Plan provides a broad explanation of what a specific ministry will do over a set timeframe at a high level; specifically, a three-fiscal-year timeframe. The Ministry business plan contains goals and high-level strategies that will be implemented by the ministry to achieve its goals. The business plan also identifies measures of progress toward the ministry’s goals as well as the Ministry operating budget allocated in pursuit of these goals.' },
    { term : 'Net Promoter Score (NPS)', definition: 'Continuously tracking performance and providing regular updates on service status and metrics.' },
    { term : 'Observable Outputs', definition: 'Teams composed of members with diverse expertise (e.g., designers, researchers, policy experts) to ensure comprehensive service development.' },
    { term : 'Ongoing Performance Evaluation', definition: 'Measures user loyalty by asking users how likely they are to recommend the service to others on a scale of 0 to 10.' },
    { term : 'Open Source Data', definition: 'Specific, measurable results that demonstrate the effectiveness of a digital service.' },
    { term : 'Open standards', definition: 'Regular assessment of service performance throughout its lifecycle to ensure continuous improvement.' },
    { term : 'Open-source and reusable components', definition: 'promotes a collaborative environment where developers from around the globe contribute to and scrutinize the code. This collective effort not only accelerates innovation but also enhances security through continuous peer review. Governments and public sector organizations leveraging open-source can reduce costs significantly, as there are no licensing fees involved, and ensure greater flexibility in customizing applications to meet specific needs' },
    { term : 'Operational Metrics', definition: 'Publicly available guidelines or specifications that ensure interoperability and compatibility across different systems and services.' },
    { term : 'Operational Uptime', definition: 'Where possible, software development efforts should leverage open-source components and frameworks to reduce development time and costs and promote sharing and collaboration. This would also promote efficient use of public resources.' },
    { term : 'Outcome Metrics', definition: 'Measures that track the day-to-day functioning and efficiency of digital services.' },
    { term : 'Performance and Reliability', definition: 'The percentage of time the digital service is fully operational and available to users.' },
    { term : 'Performance Dashboards', definition: 'Measures that focus on the end results or impacts of a digital service.' },
    { term : 'Performance Framework', definition: 'The tools and technologies demonstrate reliable performance under expected workloads and conditions. They meet performance benchmarks and service level agreements (SLAs) consistently, minimizing downtime and disruptions to operations.' },
    { term : 'Performance Measures', definition: 'Visual tools that display real-time performance data and metrics for digital services.' },
    { term : 'Plain language', definition: 'A structured approach to setting, measuring, and reporting on the performance metrics of digital services.' },
    { term : 'Platform', definition: 'Quantitative indicators used to assess how well a digital service is performing.' },
    { term : 'Presentation', definition: 'Writing and designing content that is clear and easy to understand, avoiding technical jargon and complex terms.' },
    { term : 'Privacy and security', definition: 'A computer or hardware device and/or associated operating system, or a virtual environment, on which software can be installed or run' },
    { term : 'Privacy Impact Assessment (PIA)', definition: 'The process of transferring the digital credential from Holder to Verifier (e.g., Near Field Communication, Bluetooth, Verification over IP, QR Code).' },
    { term : 'Privacy measures', definition: 'We handle sensitive information, and it is crucial to ensure that software development practices prioritize privacy and security. This includes implementing robust data protection and security measures to protect sensitive information and following best practices for secure software development.' },
    { term : 'Processing Time ', definition: 'A privacy impact assessment is a process that assists public bodies in reviewing the impact that a new program, administrative process or practice, information system or legislation may have on individual privacy. The process is designed to ensure that the public body evaluates the project or initiative for technical compliance with the FOIP Act and also assesses the broader privacy implications for individuals.' },
    { term : 'Product', definition: 'Policies and practices implemented to protect user data and ensure compliance with legal and ethical standards.' },
    { term : 'Product', definition: 'Measures the average time taken to complete a service transaction from start to finish.' },
    { term : 'Product and Delivery Lead', definition: 'A digital tool or application created to meet specific user needs and solve problems, typically offered to users as a complete package.' },
    { term : 'Product Backlog', definition: 'The product can be tangible (something physical which one can touch) or intangible (like a service or experience), though sometimes services and other processes are distinguished from "products".' },
    { term : 'Product Champion', definition: 'coaches and supports the team to make sure agile and service design best practices are followed.' },
    { term : 'Product Market Fit', definition: '​Ideas, features, bugs and enhancements that are often expressed as user stories.' },
    { term : 'Product Market Fit', definition: 'Provides the product vision (and often funding) for the project. Having a clear project vision is imperative, as team members rely on this vision to maintain direction and momentum throughout the project life cycle.​' },
    { term : 'Product Metrics', definition: 'The degree to which a product satisfies a strong market demand, indicating a good alignment between the product\'s offerings and the needs of its target audience.' },
    { term : 'Product Owner', definition: 'Product-market fit describes a scenario in which a company’s target customers are buying, using, and telling others about the company’s product in numbers large enough to sustain that product’s growth and profitability.' },
    { term : 'Product Owner', definition: 'Quantitative measures used to evaluate the performance, usage, and success of a digital product, informing ongoing improvements and decision-making.' },
    { term : 'Product Performance Metrics', definition: 'A subject matter expert who prioritizes the user stories (requirements) based on the vision and the stakeholders and execution team’s input.' },
    { term : 'Product Team', definition: 'the visionary that guides the development of a product to meet user needs.' },
    { term : 'Product Team', definition: 'Metrics that assess the efficiency, reliability, and speed of a digital product, ensuring it meets user expectations and performs well under various conditions.' },
    { term : 'Productivity Rate', definition: 'A small, empowered, self- organizing, multi-disciplinary team (6-8 people), that works together to deliver a product or service.' },
    { term : 'Project', definition: 'A multidisciplinary team consisting ofr product owner, service designers, program SMEs, UX and quality assurance.' },
    { term : 'Project', definition: 'anything that could be measured from internal staff work, i.e. average support call times, support calls per transaction, average time for specific tasks, duplicate tasks, number of systems, websites, tools used to deliver service. ' },
    { term : 'Project Delivery Time', definition: 'A temporary endeavor undertaken to create a unique product, service, or result, often involving defined objectives, timelines, and resources.' },
    { term : 'Proof of Concept (POC)', definition: 'A project is a temporary organization, usually existing for a short duration, which will deliver one or more outputs in accordance with a specific business case. It is a structured set of activities concerned with delivering to the enterprise a defined capability that is necessary, but not sufficient, to achieve a required business outcome based on an agreed schedule and budget.' },
    { term : 'Prototype', definition: 'Measures the average time taken to complete an agile project from inception to delivery.' },
    { term : 'Prototype', definition: 'In software development, a POC (Proof of Concept) is used in Discovery to evaluate whether a proposed solution aligns with the business goals. We should check if the proposed solution solves the business and user problems and if it is scalable.' },
    { term : 'Proxy Performance Measures', definition: 'Prototypes are simplified and visual versions used to test design, usability, or functionality, focusing on one of these elements. They exemplify the final solution and assist in the approval of experience and design details, especially with stakeholders.' },
    { term : 'Public-facing services', definition: 'A prototype is an early version of a product from which future versions are developed. Engineers and product developers often create these test versions of a new product, service or device before releasing it.' },
    { term : 'Quality Assurance', definition: 'Measures that approximate service performance, used when direct measurement is not possible.' },
    { term : 'Resource Utilization Rate', definition: 'Digital services designed and implemented for use by the general public, including citizens and businesses.' },
    { term : 'Risk', definition: 'The process of ensuring that digital services meet predefined quality standards and performance criteria.' },
    { term : 'Risk Management', definition: 'Measures the percentage of allocated resources (staff, budget) that are effectively used in project execution.' },
    { term : 'Risk ​', definition: 'Potential that a given threat will exploit the vulnerability of an asset or group of assets to cause loss or damage to the assets.' },
    { term : 'Scalability', definition: 'Identifying, assessing, and mitigating risks that could impact the performance and delivery of digital services.' },
    { term : 'Scalability', definition: 'Because of the transparency and short work cycles, risk is reduced. With Waterfall, a client gets what they asked for, but not necessarily what they want/need. With Waterfall teams generally are making all decisions when have least amount of knowledge. ​' },
    { term : 'Scalability', definition: 'The capability of a digital service to handle increased usage and demand without compromising performance, ensuring it can grow and adapt to user needs.' },
    { term : 'Scalability and sustainability', definition: 'The tools and technologies have the scalability to accommodate future growth and changes in requirements. They can handle increasing volumes of data, users, or transactions without significant performance degradation or architectural constraints.  ' },
    { term : 'Scrum Master', definition: 'The ability of a digital service to handle increased usage or expansion without compromising performance.' },
    { term : 'Scrum (Development) Team', definition: 'Software should be designed to be scalable and sustainable, to accommodate growth and future requirements.' },
    { term : 'Security and Privacy', definition: 'Removes obstacles to the development process and facilitates the team progress from a collection of individuals towards becoming a high-performance team​ (the Scrum Master is a member of the Scrum team). ' },
    { term : 'Security measures', definition: 'Gathers requirements (user stories) and builds the system.' },
    { term : 'Security Threat Risk Assessment (STRA)', definition: 'Prioritize tools and technologies that have robust security features and a good track record for addressing vulnerabilities. Data protection, encryption, authentication, and compliance with industry standards are essential considerations, especially for applications handling sensitive information.  ' },
    { term : 'Selective Disclosure ', definition: 'Techniques and protocols used to safeguard digital services and user data from unauthorized access and malicious activities.' },
    { term : 'Self-Serve Interactions', definition: 'A component of a risk analysis specifically aimed at identifying security exposures.' },
    { term : 'Service', definition: 'The privacy-protecting feature of allowing the holder to choose which elements of a digital credential to include in the presentation.' },
    { term : 'Service', definition: 'Interactions where users can complete tasks on their own without needing assistance, enhancing efficiency and user satisfaction.' },
    { term : 'Service Accessibility Index', definition: 'A service is any activity that helps someone complete a task. With that in mind, all public servants – whether they work in digital, communications, policy or operations – are involved in service design.' },
    { term : 'Service adoption', definition: 'A service is the provision of a specific final output that addresses one or more needs of an intended recipient and contributes to the achievement of an outcome.' },
    { term : 'Service Blueprint', definition: 'Measures the availability and usability of the digital service across various devices (e.g., smartphones, tablets, desktops), assistive technologies (e.g., screen readers) and by citizens with different disability levels.' },
    { term : 'Service Completion Rate', definition: 'The extent to which users engage with and utilize digital services, reflecting their accessibility and effectiveness.' },
    { term : 'Service Continuity', definition: 'A detailed visual representation of the service delivery process, including interactions, touchpoints, and performance metrics.' },
    { term : 'Service Cost Efficiency / Cost per transaction', definition: 'Measures the percentage of service requests successfully completed.' },
    { term : 'Service Customization', definition: 'Ensuring that digital services remain available and functional during and after disruptions.' },
    { term : 'Service disruptors', definition: 'Measures the cost per transaction for providing the service.' },
    { term : 'Service Enhancement Prioritization', definition: 'Tailoring digital services to meet the specific needs and preferences of different user groups.' },
    { term : 'Service enhancements', definition: 'Potential issues or changes that could impact the delivery and performance of digital services, such as technological advancements or security threats.' },
    { term : 'Service Governance', definition: 'Process of deciding which service improvements to implement based on performance data and user feedback.' },
    { term : 'Service interaction', definition: 'Improvements or updates made to digital services to better meet user needs and improve overall performance.' },
    { term : 'Service lifecycle', definition: 'The processes and mechanisms needed to coordinate and manage the use of IT-related activities and resources to meet the operative and strategic goals of the company providing the services.' },
    { term : 'Service Lifecycle Management', definition: 'The ways in which users engage with and use digital services, including interfaces, processes, and support channels.' },
    { term : 'Service Metrics', definition: 'The stages a digital service goes through from initial concept and development to deployment, maintenance, and eventual decommissioning.' },
    { term : 'Service Owner', definition: 'The process of overseeing the entire lifecycle of a digital service, from conception to decommissioning.' },
    { term : 'Service Owner (GoC)', definition: 'Quantitative measures used to assess various aspects of digital service performance.' },
    { term : 'Service performance platform', definition: 'The service owner is the person who has the primary responsibility to ensure that a service delivers what it promises. The service owner is the primary point of contact for the service, and has final responsibility for decision-making or escalation of decisions.' },
    { term : 'Service Performance Platform', definition: 'A service owner is the organization that has the authority to offer the service. That authority is often conferred through legislation or through a regulatory or other instrument, and accountability is delegated to the appropriate level of manager.' },
    { term : 'Service Reliability', definition: 'A system for tracking and analyzing the effectiveness and efficiency of digital services based on defined performance metrics.' },
    { term : 'Service Reliability Engineering', definition: 'A system for tracking and analyzing the effectiveness and efficiency of digital services based on defined performance metrics.' },
    { term : 'Service Reliability Rate', definition: 'Ensuring digital services operate consistently and meet user expectations without frequent interruptions.' },
    { term : 'Service Resiliency', definition: 'Practices and techniques used to ensure that digital services are reliable and perform consistently.' },
    { term : 'Service Roadmap', definition: 'Measures the percentage of time the digital service is available and operational without outages or significant issues.' },
    { term : 'Service Uptake', definition: 'The ability of a digital service to adapt to changes and maintain performance under various conditions.' },
    { term : 'Service-Level Agreements (SLAs)', definition: 'A strategic plan outlining the future development and improvement of a digital service.' },
    { term : 'Stakeholder Engagement', definition: 'The rate at which new users start using the digital service, indicating its adoption and popularity.' },
    { term : 'Standard Operating Procedures (SOPs)', definition: 'Contracts that define the expected level of service performance and responsibilities between service providers and users.' },
    { term : 'Success Rate', definition: 'Actively involving stakeholders in the service design and delivery process to ensure their needs are met.' },
    { term : 'System Failures', definition: 'Documented procedures that guide the consistent execution of tasks and processes in digital service delivery.' },
    { term : 'Task Completion Rates', definition: 'The percentage of transactions that users successfully complete on the digital service.' },
    { term : 'Team Velocity', definition: 'Failures in the system that can disrupt the delivery of digital services.' },
    { term : 'Technology Changes', definition: 'Metrics that measure how often users successfully complete tasks using a digital service.' },
    { term : 'Technology Integration', definition: 'Measures the amount of work a team completes during a sprint, usually quantified in story points or tasks.' },
    { term : 'Transparency', definition: 'Adjustments made to accommodate new technologies impacting service delivery.' },
    { term : 'Transparency', definition: 'The process of ensuring different technologies used in a digital service work together seamlessly.' },
    { term : 'Transparency and accountability', definition: 'The practice of making information, processes, and decision-making open and accessible to build trust and collaboration.' },
    { term : 'Trend Analysis', definition: 'In the context of Information and Communication Technology (ICT), the term describes the need for clarity about how information is created, processed, managed, transmitted, stored, and shared. Transparency helps stakeholders identify potential bottlenecks and areas for improvement. It also helps ensure accountability.' },
    { term : 'UIAM', definition: 'We should be transparent in their operations and software development processes. This includes being transparent about the data they collect, how it is used, and who has access to it. With the transparency in development and deployment, there would be accountability to provide best services to citizens.' },
    { term : 'Understandable', definition: 'Monitoring and analyzing performance data over time to identify patterns and measure changes in service performance.' },
    { term : 'Usability Benchmarking', definition: 'Identity and access management solution used to make it possible to verify and manage identities, detect suspicious activity and report incidents: security measures are intended to add a level of protection to your personal and corporate information.' },
    { term : 'Usability Metrics', definition: 'Digital products can be broadly understood by the largest user base possible by presenting information in plain language, absent of organizational speak, industry jargon, and complex legalese' },
    { term : 'Usability testing', definition: 'Comparing the usability of a digital service against established standards or other services to identify areas for improvement.' },
    { term : 'Usability Testing', definition: 'Measures that assess how easy and intuitive a digital service is for users.' },
    { term : 'Usable', definition: 'Evaluating a digital service by testing it with real users to identify usability issues and areas for improvement.' },
    { term : 'Usage Spikes', definition: 'Evaluating a digital service by testing it with real users to identify usability issues and areas for improvement.' },
    { term : 'User ', definition: 'Using human-centered design to understand users’ context of use, goals, tasks, and environments' },
    { term : 'User Behavior Metrics', definition: 'Sudden increases in usage that can affect service performance.' },
    { term : 'User Engagement Metrics', definition: 'All persons authorized to access the government information or information technology systems including employees and contractors.' },
    { term : 'User feedback', definition: 'Measures that analyze user actions within a digital service, such as navigation patterns, feature usage, and completion rates, providing insights into user preferences.' },
    { term : 'User Feedback and Satisfaction', definition: 'Indicators that measure how users interact with a digital service, including frequency, duration, and depth of interactions, helping to gauge user interest and value.' },
    { term : 'User Feedback Metrics', definition: 'Information and opinions provided by users regarding their experiences with digital services, used to inform improvements and enhancements.' },
    { term : 'User Feedback Metrics', definition: 'Solicit feedback from end-users, stakeholders, and team members about their experiences with the chosen tools and technologies. Positive feedback and high user satisfaction indicate that the tools meet their needs and expectations effectively.' },
    { term : 'User Journey Mapping', definition: 'Data collected from user opinions and experiences regarding a digital service, used to inform enhancements and address pain points.' },
    { term : 'User Onboarding', definition: 'Data collected from user opinions and experiences regarding a digital service, used to inform enhancements and address pain points.' },
    { term : 'User Persona Profiles', definition: 'Visualizing the steps users take to interact with a digital service to identify pain points and opportunities for improvement.' },
    { term : 'User Satisfaction', definition: 'The process of introducing new users to a digital service and helping them understand how to use it effectively.' },
    { term : 'User Satisfaction (CSAT) Score', definition: 'Detailed descriptions of typical users, their needs, and behaviors used to guide service design and development.' },
    { term : 'User Satisfaction Score', definition: 'The degree to which users are happy with a digital service, often measured through surveys and feedback.' },
    { term : 'User value', definition: 'Measures the average satisfaction rating given by users after interacting with a specific digital service.' },
    { term : 'User value', definition: 'Represents the average satisfaction rating given by users after interacting with a digital service.  Measured on a scale from 1 to 5.' },
    { term : 'User Value', definition: 'The benefits and positive outcomes that users receive from interacting with a digital service, reflecting its effectiveness and relevance to their needs.' },
    { term : 'User-Centered Design', definition: 'The benefits and positive outcomes users receive from engaging with digital services, reflecting their effectiveness and relevance.' },
    { term : 'User-centred products', definition: 'The benefits and positive outcomes users receive from interacting with a digital service.' },
    { term : 'User-centric Agility and collaboration', definition: 'Designing digital services with a focus on the needs and experiences of end-users.' },
    { term : 'User-centric approach', definition: 'Digital products developed with a focus on the needs and experiences of the end-users, ensuring that the services are accessible and beneficial to all users.' },
    { term : 'Verifiers', definition: 'The tools and technologies align closely with the requirements, objectives, and constraints of the product. They address the specific needs of the service and enable business to achieve their goals effectively. ' },
    { term : 'Visibility', definition: 'The primary focus of software development should be on the needs and requirements of citizens. Software should be designed and developed with the end-user in mind, taking into account their pain points, preferences, and feedback.' },
    { term : 'Waterfall', definition: 'Parties receiving a presentation of a digital credential at the point of service, who need to verify its authenticity with the identifier or issuer’s public key (e.g., a health-care provider).' },
    { term : 'Waterfall', definition: 'Agile processes should be transparent to all involved. With Waterfall, the client only sees the finished product at the end of the process.' },
];