name: ZAP automation

on:
  workflow_dispatch:
    inputs:
      BRANCH_NAME:
        description: 'Name of the branch to run the scan on'
        required: true
      TARGET_URL:
        description: 'URL to target for the ZAP scan'
        required: true
      DOMAIN:
        description: 'Domain to use in auth context for the scan'
        required: true
      DOMAIN_POLL:
        description: 'Domain to poll to use in auth context for the scan'
        required: true

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.BRANCH_NAME }}

      - name: Replace placeholders
        run: |
          sed -i "s|DOMAIN_PLACEHOLDER|${{ github.event.inputs.DOMAIN }}|g" zap/automation.yml
          sed -i "s|DOMAIN_POLL_PLACEHOLDER|${{ github.event.inputs.DOMAIN_POLL }}|g" zap/automation.yml
          sed -i "s|USER_PLACEHOLDER|${{ secrets.ZAP_SSO_USER }}|g" zap/automation.yml
          sed -i "s|PASSWORD_PLACEHOLDER|${{ secrets.ZAP_SSO_PWD }}|g" zap/automation.yml

      - name: ZAP Automation Framework Scan
        uses: zaproxy/action-af@v0.2.0
        with:
          plan: 'zap/automation.yml'